# Generated by Django 5.0.6 on 2024-07-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(default='manual', max_length=100)),
                ('name', models.CharField(default='Manually Added', max_length=100)),
                ('description', models.TextField(default='This contact was manually added to the database.')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, help_text='The first name of the contact.', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='The last name of the contact.', max_length=100)),
                ('email', models.EmailField(help_text='The email address of the contact.', max_length=254, unique=True)),
                ('company', models.CharField(blank=True, help_text='The company of the contact.', max_length=100)),
                ('address', models.CharField(blank=True, help_text='The address of the contact.', max_length=255)),
                ('title', models.CharField(blank=True, help_text='The title of the contact.', max_length=5)),
                ('phone', models.CharField(blank=True, help_text='The phone number of the contact.', max_length=20)),
                ('birthday', models.DateField(blank=True, help_text='The birthday of the contact.', null=True)),
                ('recently_contacted', models.BooleanField(default=False, help_text='Whether the contact was recently contacted in a campaign or not.')),
                ('recently_bounced', models.BooleanField(default=False, help_text='Whether the contact recently bounced in one of the campiagns or not.')),
                ('subscribed', models.BooleanField(default=True, help_text='Whether the contact is subscribed or not.')),
                ('source', models.CharField(blank=True, help_text='The source of the contact.', max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Any tags you want for this contact seperated by commas.', max_length=255)),
                ('method', models.ForeignKey(help_text='The method used to add the contact.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.method')),
            ],
        ),
    ]
