# Generated by Django 5.0.6 on 2024-07-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='method',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
    ]
