# Generated by Django 5.0.6 on 2024-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_contact_method_delete_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tag.', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags of the contact.', to='main.tag'),
        ),
    ]
