# Generated by Django 5.0.6 on 2024-07-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag_remove_contact_tags_contact_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
