# Generated by Django 5.0.6 on 2024-07-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, help_text='The title of the import.', max_length=100)),
                ('contacts', models.ManyToManyField(blank=True, help_text='The contacts of the import.', to='main.contact')),
            ],
        ),
    ]
