# Generated by Django 5.0.6 on 2024-07-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_import'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import',
            old_name='title',
            new_name='import_title',
        ),
    ]
