# Generated by Django 5.0.7 on 2024-07-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_title_import_import_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='auto_unmark',
            field=models.IntegerField(default=0, help_text='The number of days to wait before unmarking the contact as `recently_contacted`, put "0" to manually unmark.'),
        ),
    ]
