# Generated by Django 5.0.6 on 2024-07-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact_auto_unmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags of the contact.', null=True, to='main.tag'),
        ),
    ]
